# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # TOOLS #
    app.slugger:
        class: AppBundle\Tools\Slugger

    # FORMS #
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    # CUSTOM FORM FIELDS TYPES
    app.type.movie_selector:
        class: AppBundle\Form\Type\MovieSelectorType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: movie_selector }

    # TRIGGERS #
    app.subscriber.file.upload:
        class: AppBundle\EventListener\FileUploadSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }